theme: jekyll-theme-midnight
title: openshift-kafka - fork
description: Run Apache Kafka and Apache ZooKeeper on OpenShift v3.
show_downloads: false
# google_analytics: UA-104415848-1
url: https://ashokhin.github.io
author: Andrey Shokhin
logo: /openshift-kafka/assets/logo.png

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      categories: [milk, pumpkin pie, eggs, juice]
      tags: [milk, pumpkin pie, eggs, juice]
plugins:
  - jekyll-seo-tag
