name: Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    name: Create and publish docker image
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_REPO_NAME }}/openshift-kafka
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
